---
- name: Creating directory in etc for blackbox_exporter
  file:
    path: /etc/blackbox_exporter
    state: directory

- name: Configuring blackbox_exporter
  template:
    src: blackbox_exporter.yml.j2
    dest: /etc/blackbox_exporter/blackbox_exporter.yml
    owner: "{{blackbox_exporter_user}}"
    group: "{{blackbox_exporter_group}}"
    mode: 0644

- name: Creating systemd service unit
  template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart blackbox exporter
