---
# tasks file for blackbox_exporter
- include_tasks: blackbox_exporter.yml

- name: Starting and enabling blackbox exporter
  systemd:
    daemon_reload: true
    name: blackbox_exporter
    state: started
    enabled: true
